### ISSUE TITLE
Removing node teamkill notification from chat

### ISSUE THREAD

**Issue by ZefSilica** [data-bomb/Silica#33]
Can you remove the notification that pops up in chat when someone kills a node?

People often follow nodelines to find Alien buildings. A counter tactic is to remove the nodes towards important buildings like the Quantum Cortex or Nest. This way you can hide buildings but right now every node you remove tells everyone in chat what you are doing.

**Comment by data-bomb** [comment]
This is good feedback to hear. The Anti-Grief mod is responsible for sending out the Node messages right now. This is a valid tactic for the Alien team that I didn't fully consider when adding the notification for FF structure kills into Anti-Grief. It's currently harmful for the mod to broadcast that Nodes are being killed since this reveals the strategy to the human teams.
